{{- $svc := .Values.microservices["auth-service"] -}}

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: {{ $svc.image }}
        ports:
        - containerPort: {{ $svc.port }}
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "{{ $.Values.global.otelEndpoint }}"
        - name: OTEL_SERVICE_NAME
          value: "auth-service"

  strategy:
    canary:
      stableService: auth-service-stable
      canaryService: auth-service-canary
      steps:
      - setWeight: 20
      - pause: { duration: 20s }
      - setWeight: 60
      - pause: { duration: 20s }
      - setWeight: 100

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-stable
spec:
  selector:
    app: auth-service
    rollouts-pod-template-hash: stable
  ports:
  - port: {{ $svc.port }}
    targetPort: {{ $svc.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-canary
spec:
  selector:
    app: auth-service
    rollouts-pod-template-hash: canary
  ports:
  - port: {{ $svc.port }}
    targetPort: {{ $svc.port }}
