apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app: cart-service
    release: prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.cart.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - name: http
      port: {{ .Values.cart.port }}
      targetPort: {{ .Values.cart.port }}
