{{- $svc := .Values.microservices["frontend"] -}}

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ $svc.image }}
        ports:
        - containerPort: {{ $svc.port }}
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "{{ $.Values.global.otelEndpoint }}"
        - name: OTEL_SERVICE_NAME
          value: "frontend"

  strategy:
    canary:
      stableService: frontend-stable
      canaryService: frontend-canary
      steps:
      - setWeight: 20
      - pause: { duration: 20s }
      - setWeight: 60
      - pause: { duration: 20s }
      - setWeight: 100

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-stable
spec:
  selector:
    app: frontend
    rollouts-pod-template-hash: stable
  ports:
  - port: {{ $svc.port }}
    targetPort: {{ $svc.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-canary
spec:
  selector:
    app: frontend
    rollouts-pod-template-hash: canary
  ports:
  - port: {{ $svc.port }}
    targetPort: {{ $svc.port }}
