apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-service
    release: prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.orders.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: orders-service
  ports:
    - name: http
      port: {{ .Values.orders.port }}
      targetPort: {{ .Values.orders.port }}
