{{- $svc := .Values.microservices["orders-service"] -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: {{ $svc.image }}
        ports:
        - containerPort: {{ $svc.port }}
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "{{ $.Values.global.otelEndpoint }}"
        - name: OTEL_SERVICE_NAME
          value: "orders-service"

---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-service
    release: prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ $svc.port }}"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: orders-service
  ports:
  - port: {{ $svc.port }}
    targetPort: {{ $svc.port }}
  type: ClusterIP

