{{- /*
Safe Service template for products-service.
Uses index+default to avoid nil-pointer errors when .Values.products or .Values.products.port is missing.
*/ -}}

{{- $defaultPort := 3001 -}}
{{- $port := default $defaultPort (index .Values "products" "port") -}}

apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: products-service
    release: prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ $port }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: products-service
  ports:
    - name: http
      port: {{ $port }}
      targetPort: {{ $port }}
