{{- /*
Safe products Deployment template.
Uses `if` blocks to avoid nil-pointer access to .Values.products.
Provides defaults for image, replicas and port.
*/ -}}

{{- if .Values.products }}
  {{- $image := default "sreedocker123/cafemicroserviceproducts:latest" .Values.products.image }}
  {{- $replicas := default 1 .Values.products.replicas }}
  {{- $port := default 3001 .Values.products.port }}
{{- else }}
  {{- $image := "sreedocker123/cafemicroserviceproducts:latest" -}}
  {{- $replicas := 1 -}}
  {{- $port := 3001 -}}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  labels:
    app: products-service
spec:
  replicas: {{ if .Values.products }}{{ default 1 .Values.products.replicas }}{{ else }}1{{ end }}
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: {{ if .Values.products }}{{ default "sreedocker123/cafemicroserviceproducts:latest" .Values.products.image }}{{ else }}"sreedocker123/cafemicroserviceproducts:latest"{{ end }}
          ports:
            - containerPort: {{ if .Values.products }}{{ default 3001 .Values.products.port }}{{ else }}3001{{ end }}
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ default "http://otel-collector:4318/v1/traces" .Values.global.otelCollector | quote }}
            - name: OTEL_SERVICE_NAME
              value: "products-service"
          # optional: add readiness/liveness probes if you want
