{{- /*
Safe Service template for products-service.
This template never panics if .Values.products or .Values.products.port is missing.
It uses inline if/default checks so the port falls back to 3001.
*/ -}}

{{- $defaultPort := 3001 -}}

apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: products-service
    release: prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ if .Values.products }}{{ default $defaultPort .Values.products.port }}{{ else }}{{ $defaultPort }}{{ end }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: products-service
  ports:
    - name: http
      port: {{ if .Values.products }}{{ default $defaultPort .Values.products.port }}{{ else }}{{ $defaultPort }}{{ end }}
      targetPort: {{ if .Values.products }}{{ default $defaultPort .Values.products.port }}{{ else }}{{ $defaultPort }}{{ end }}
